#!/usr/bin/env python3
"""Generate shaders_embedded.cpp: every GLSL source (and, for Vulkan builds,
every compiled SPIR-V blob) baked into the executable as a lookup table.

The RHI shader loaders consult this table LAST (VFS -> dev source dir ->
embedded), so a bare binary always has working GL3/Vulkan renderers while
modders/devs can still override via base/shaders/ or the source tree.

Usage: embed_shaders.py --glsl <dir> --out <file.cpp> [--spv <dir>]
"""
import argparse
import os
import sys

GLSL_EXTS = {".vert", ".frag", ".tesc", ".tese", ".glsl"}


def emit_blob(out, sym, data):
    out.write(f"static const unsigned char {sym}[] = {{\n")
    for i in range(0, len(data), 20):
        out.write("\t" + ",".join(str(b) for b in data[i:i + 20]) + ",\n")
    out.write("};\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--glsl", required=True)
    ap.add_argument("--spv")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    entries = []  # (lookup_name, bytes)
    for fn in sorted(os.listdir(args.glsl)):
        if os.path.splitext(fn)[1] in GLSL_EXTS:
            with open(os.path.join(args.glsl, fn), "rb") as f:
                entries.append((fn, f.read()))
    if args.spv and os.path.isdir(args.spv):
        for fn in sorted(os.listdir(args.spv)):
            if fn.endswith(".spv"):
                with open(os.path.join(args.spv, fn), "rb") as f:
                    entries.append(("spv/" + fn, f.read()))

    if not entries:
        sys.exit("embed_shaders.py: no shader inputs found")

    with open(args.out, "w") as out:
        out.write("// GENERATED by shaders/embed_shaders.py - do not edit.\n")
        out.write("// Embedded shader table: GLSL sources + SPIR-V blobs.\n\n")
        out.write("#include <string.h>\n\n")
        for i, (_, data) in enumerate(entries):
            emit_blob(out, f"blob{i}", data)
        out.write("\nstruct EmbeddedShaderEntry { const char *name; const unsigned char *data; int len; };\n")
        out.write("static const EmbeddedShaderEntry embeddedShaders[] = {\n")
        for i, (name, data) in enumerate(entries):
            out.write(f'\t{{ "{name}", blob{i}, {len(data)} }},\n')
        out.write("};\n\n")
        out.write("extern \"C\" bool Dude_GetEmbeddedShader( const char *name, const unsigned char **data, int *len ) {\n")
        out.write("\tfor ( unsigned int i = 0; i < sizeof( embeddedShaders ) / sizeof( embeddedShaders[0] ); i++ ) {\n")
        out.write("\t\tif ( strcmp( embeddedShaders[i].name, name ) == 0 ) {\n")
        out.write("\t\t\t*data = embeddedShaders[i].data; *len = embeddedShaders[i].len;\n")
        out.write("\t\t\treturn true;\n")
        out.write("\t\t}\n")
        out.write("\t}\n\treturn false;\n}\n")
    print(f"embed_shaders.py: embedded {len(entries)} shader files into {os.path.basename(args.out)}")


if __name__ == "__main__":
    main()
